<a href="https://colab.research.google.com/github/Tin1209/Study-Pytorch/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 선형회귀분석(Linear Regression)   
   
   
## 1. 선형회귀분석이란?   

선형회귀분석이란 주어진 데이터를 가장 잘 설명하는 하나의 직선을 찾는 것이다.  
하나의 독립변수에 대하여 선형회귀분석을 하는 경우 __단순선형회귀(simple linear regression)__라 하며,   
여러개의 독립변수에 대하여 선형회귀분석을 하는 경우 __다중선형회귀(multivariate linear regression)__이라 한다.  

단순선형회귀분석은 $x$와 $y$라는 데이터가 주어졌을때, 데이터를 가장 잘 표현하는 $y = wx + b$ 꼴의 직선을 찾는 것이다.   
여기서 $w$는 __가중치(weight)__, $b$는 __편차(bias)__라 한다.    


## 2. 손실 함수 및 경사하강법   
  

데이터를 가장 잘 표현한다는 말을 수학적으로 표현하면 $y = wx + b$ 를 통해 예측한 $\hat{y}$ 와 실제 결과값 $y$를 비교하는 것이다.   
이때 비교하는 방법 중 대표적인 것으로 __평균제곱오차(mean squared error-MSE)__가 있다.  
평균제곱오차 식은 다음과 같다.  $$MSE = \frac{1} {n}  \sum_{i = 1}^n (\hat{y} - y)^2$$   
이렇게 오차를 나타내는 함수를 흔히 __손실 함수(Loss function)__ 또는 __비용 함수(Cost function)__ 이라고 한다. MSE는 이러한 Cost function 중에 하나이다. 

여기서 Cost function을 최소화하는 $w$와 $b$를 찾기위해 __경사하강법(Gradient descent)__이라는 방법을 사용한다. 여기서 경사란 함수의 기울기를 의미한다.   
Cost function에서 주어진 $w$에 대한 기울기를 구하고, 그 기울기를 바탕으로 다음 $w$를 업데이트 함으로써 오차의 극솟값을 찾아준다. 식으로 표현하면 다음과 같다.
$$ w_{t+1} = w_{t} - gradient * learning\ rate $$  
여기서 __학습률(learning rate)__이 새로 나오는데, 학습률은 변수 $w$를 얼마나 업데이트할지 결정하는 수치이다.   

## 3. 파이토치에서 경사하강법  

파이토치에서는 데이터의 기본 단위로 다차원 배열인 텐서(Tensor)를 사용한다.   


In [ ]:
import torch
X = torch.Tensor(2, 3)
print(X)

tensor([[2.8181e-35, 0.0000e+00, 3.9236e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


위의 코드를 실행시키면 1행에서는 파이토치의 프레임워크를 불러오고,  
2행에서는 X라는 변수에 임의의 난수를 원소로 갖는 2x3 형태의 텐서를 생성해서 지정한다.    

In [ ]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(X)

tensor([[1, 2, 3],
        [4, 5, 6]])


위의 코드처럼 텐서를 생성할때 직접 shape과 element들을 지정해줄 수 있다.   
torch.tensor 함수는 인수로 data, dtype, device, requires_grad 등을 받는다.  
data에는 위의 코드처럼 배열이 들어가고,  
dtype에는 데이터의 자료형이 들어간다. 자료형을 지정해주지 않을시 기본 자료형은 Float로 들어간다. 
device에는 이 텐서를 어느 기기에 올릴 것인지를 명시한다.   
requires_grad는 이 텐서에 대한 기울기를 저장할지에 대한 여부를 지정한다.  

아래의 코드는 기울기를 계산하는 코드이다. 

In [ ]:
x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
y = x**2
z = 2*y + 3

target = torch.tensor([3.0, 4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  if __name__ == '__main__':
